// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_b5Uc_Mc409ziPjNqIp5fhd0ch4HIWjE',
    appId: '1:843533343549:web:01893555de77e01d38c354',
    messagingSenderId: '843533343549',
    projectId: 'ivee-a3512',
    authDomain: 'ivee-a3512.firebaseapp.com',
    storageBucket: 'ivee-a3512.firebasestorage.app',
    measurementId: 'G-M8Z0XRSJCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBckBp4RW0kWY6WMHJZ-ML0hCT18jTxLuk',
    appId: '1:843533343549:android:e056d831e6e05a5b38c354',
    messagingSenderId: '843533343549',
    projectId: 'ivee-a3512',
    storageBucket: 'ivee-a3512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlfH9jNOtjg2IIp_UYTie-cLJA8wwaUJs',
    appId: '1:843533343549:ios:b2e1108754b4dbca38c354',
    messagingSenderId: '843533343549',
    projectId: 'ivee-a3512',
    storageBucket: 'ivee-a3512.firebasestorage.app',
    iosBundleId: 'com.example.ivee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlfH9jNOtjg2IIp_UYTie-cLJA8wwaUJs',
    appId: '1:843533343549:ios:b2e1108754b4dbca38c354',
    messagingSenderId: '843533343549',
    projectId: 'ivee-a3512',
    storageBucket: 'ivee-a3512.firebasestorage.app',
    iosBundleId: 'com.example.ivee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_b5Uc_Mc409ziPjNqIp5fhd0ch4HIWjE',
    appId: '1:843533343549:web:306d8568787748b338c354',
    messagingSenderId: '843533343549',
    projectId: 'ivee-a3512',
    authDomain: 'ivee-a3512.firebaseapp.com',
    storageBucket: 'ivee-a3512.firebasestorage.app',
    measurementId: 'G-NBZL1GCRNL',
  );
}
